# Generated by Django 3.0.7 on 2020-06-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20200610_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(default='abc carrot food apple'),
            preserve_default=False,
        ),
    ]
