# Generated by Django 3.0.7 on 2020-07-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20200615_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='motivation_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
